# Generated by Django 2.1.5 on 2019-01-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LexicalItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "orthographic_representation",
                    models.CharField(max_length=100),
                ),
                ("language_code", models.CharField(max_length=2)),
            ],
        )
    ]
