# Generated by Django 2.1.5 on 2019-01-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("lexicon", "0003_auto_20190130_1022")]

    operations = [
        migrations.AddField(
            model_name="featureproperty",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        )
    ]
