# Generated by Django 2.1.5 on 2019-01-29 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("lexicon", "0003_auto_20190122_0153")]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                )
            ],
        ),
        migrations.CreateModel(
            name="FeatureProperties",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                )
            ],
        ),
        migrations.CreateModel(
            name="FeatureSet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("features", models.ManyToManyField(to="lexicon.Feature")),
            ],
        ),
        migrations.AddField(
            model_name="feature",
            name="properties",
            field=models.ManyToManyField(to="lexicon.FeatureProperties"),
        ),
        migrations.AddField(
            model_name="lexicalitem",
            name="feature_set",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lexicon.FeatureSet",
            ),
        ),
    ]
