# Generated by Django 2.1.5 on 2019-01-29 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("lexicon", "0004_auto_20190129_1726")]

    operations = [
        migrations.RenameModel(
            old_name="FeatureProperties", new_name="FeatureProperty"
        ),
        migrations.AlterModelOptions(
            name="featureproperty",
            options={"verbose_name_plural": "Feature properties"},
        ),
    ]
