# Generated by Django 2.1.5 on 2019-01-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("lexicon", "0004_featureproperty_description")]

    operations = [
        migrations.RenameField(
            model_name="lexicalitem",
            old_name="language_code",
            new_name="language",
        )
    ]
