# Generated by Django 2.1.5 on 2019-01-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("lexicon", "0005_auto_20190129_1732")]

    operations = [
        migrations.AddField(
            model_name="featureproperty",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="featureproperty",
            name="value",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
