# Generated by Django 2.1.5 on 2019-01-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("lexicon", "0006_auto_20190129_1738")]

    operations = [
        migrations.AddField(
            model_name="feature",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        )
    ]
