# Main setup
dist: xenial
language: python
python: "3.6"
node_js:
  - 10

# Dependencies
services:
  - redis-server

cache:
  yarn: true
  pip: true
  directories:
    - "~/.cache/"

before_install:
  - sudo apt-get install libgconf-2-4
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source ~/.poetry/env

install:
  - poetry install
  - poetry show -v
  - yarn --prod

script:
  - chmod a+x ./build-prod && ./build-prod
  - chmod a+x ./serve-prod && ./serve-prod
  - yarn workspace cypress-testing run cypress-run

