# Main setup
dist: xenial
language: python
python: "3.6"
node_js:
  - 10

# Dependencies
services:
  - redis-server
  - postgresql

cache:
  yarn: true
  pip: true
  directories:
    - "~/.cache/"
    - "~/virtualenv/"

before_install:
  - sudo apt-get install libgconf-2-4
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source ~/.poetry/env

install:
  - poetry install
  - poetry show -v
  - yarn --prod

before_script:
  - psql -c "CREATE USER cs_toolkit WITH PASSWORD 'cs_toolkit';" -U postgres
  - psql -c "CREATE DATABASE cs_toolkit WITH OWNER cs_toolkit;" -U postgres

script:
  - yarn workspace django-backend run load-basic
  - chmod a+x ./build-prod && ./build-prod
  - chmod a+x ./serve-prod && ./serve-prod &
  - CI=true yarn workspace react-frontend run test
  - yarn workspace cypress-testing run cypress-run