# Main setup
dist: xenial
language: python
python: "3.7"
node_js:
  - "lts/*"

# Dependencies
services:
  - redis

addons:
  chrome: stable

cache:
  yarn: true
  pip: true
  directories:
    - "~/.cache/"
    - "~/virtualenv/"

before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install --yes libgconf-2-4 postgresql-11 postgresql-client-11
  - sed -e 's/^port.*/port = 5432/' /etc/postgresql/11/main/postgresql.conf > postgresql.conf
  - sudo chown postgres postgresql.conf
  - sudo mv postgresql.conf /etc/postgresql/11/main
  - sudo cp /etc/postgresql/{10,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source ~/.poetry/env

install:
  - poetry install
  - poetry show -v
  - yarn --prod

before_script:
  - psql -p 5432 -c "CREATE USER cs_toolkit WITH PASSWORD 'cs_toolkit';" -U postgres
  - psql -p 5432 -c "CREATE DATABASE cs_toolkit WITH OWNER cs_toolkit;" -U postgres

script:
  - yarn workspace django-backend run load-basic
  - chmod a+x ./build-prod && ./build-prod
  - chmod a+x ./serve-prod && ./serve-prod &
  - CI=true yarn workspace react-frontend run test
  - yarn workspace cypress-testing run cypress-run