# Main setup
dist: xenial
language: python
python: "3.7"
node_js:
  - 10

# Dependencies
services:
  - redis-server

cache:
  yarn: true
  pip: true
  directories:
    - "~/.cache/"

before_install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python

install:
  - poetry install
  - yarn --prod

script:
  - ./build-prod
  - ./serve-prod
  - yarn workspace cypress-testing run cypress-run

