#!/bin/bash

# ----------------------------------
# Colors
# ----------------------------------
NOCOLOR='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHTGRAY='\033[0;37m'
DARKGRAY='\033[1;30m'
LIGHTRED='\033[1;31m'
LIGHTGREEN='\033[1;32m'
YELLOW='\033[1;33m'
LIGHTBLUE='\033[1;34m'
LIGHTPURPLE='\033[1;35m'
LIGHTCYAN='\033[1;36m'
WHITE='\033[1;37m'

# Handling for Git Bash for Windows
case "$(uname -s)" in
   MINGW*)
     export FORCE_COLOR=true
     ;;
esac

# ----------------------------------
# React
echo -e "${CYAN}Building React frontend...${NOCOLOR}"
yarn workspace react-frontend run build

# Django
echo -e "${CYAN}Collecting Django static files (deleting old ones)...${NOCOLOR}"
yarn workspace django-backend run build

echo -e "${CYAN}Production build done.${NOCOLOR}"