# Generated by Django 2.1.7 on 2019-09-10 03:21

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [("lexicon", "0002_auto_20190410_0924")]

    operations = [
        migrations.CreateModel(
            name="Derivation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("complete", models.BooleanField(default=False)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="DerivationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("raw_lexical_array", models.TextField()),
                ("creation_time", models.DateTimeField()),
                (
                    "created_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_completion_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "derivations",
                    models.ManyToManyField(
                        related_name="derivation_requests",
                        to="grammar.Derivation",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="DerivationStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Processed", "Processed"),
                            ("Converged", "Converged"),
                            ("Crashed", "Crashed"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("rule_errors_json", models.TextField(blank=True)),
                ("generator_metadata_json", models.TextField(blank=True)),
                ("crash_reason", models.TextField(blank=True)),
                (
                    "processed_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("complete", models.BooleanField(default=False)),
                (
                    "derivations",
                    models.ManyToManyField(to="grammar.Derivation"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneratorDescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="LexicalArrayItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "derivation_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lexical_array_items",
                        to="grammar.DerivationStep",
                    ),
                ),
                (
                    "lexical_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="lexicon.LexicalItem",
                    ),
                ),
            ],
            options={"ordering": ["order"]},
        ),
        migrations.CreateModel(
            name="RuleDescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SyntacticObject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("text", models.CharField(max_length=100)),
                ("current_language", models.CharField(max_length=50)),
                ("is_copy", models.BooleanField(default=False)),
                (
                    "level",
                    models.PositiveIntegerField(db_index=True, editable=False),
                ),
                (
                    "lft",
                    models.PositiveIntegerField(db_index=True, editable=False),
                ),
                (
                    "rght",
                    models.PositiveIntegerField(db_index=True, editable=False),
                ),
                (
                    "tree_id",
                    models.PositiveIntegerField(db_index=True, editable=False),
                ),
                (
                    "deleted_features",
                    models.ManyToManyField(
                        blank=True,
                        related_name="so_deleted_set",
                        to="lexicon.Feature",
                    ),
                ),
                (
                    "features",
                    models.ManyToManyField(
                        blank=True, related_name="so_set", to="lexicon.Feature"
                    ),
                ),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="grammar.SyntacticObject",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.AddField(
            model_name="derivationstep",
            name="generators",
            field=models.ManyToManyField(
                blank=True, to="grammar.GeneratorDescription"
            ),
        ),
        migrations.AddField(
            model_name="derivationstep",
            name="previous_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_steps",
                to="grammar.DerivationStep",
            ),
        ),
        migrations.AddField(
            model_name="derivationstep",
            name="root_so",
            field=mptt.fields.TreeOneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="grammar.SyntacticObject",
            ),
        ),
        migrations.AddField(
            model_name="derivationstep",
            name="rules",
            field=models.ManyToManyField(
                blank=True, to="grammar.RuleDescription"
            ),
        ),
        migrations.AddField(
            model_name="derivationstep",
            name="sub_derivations",
            field=models.ManyToManyField(
                related_name="trigger_steps", to="grammar.Derivation"
            ),
        ),
        migrations.AddField(
            model_name="derivation",
            name="converged_steps",
            field=models.ManyToManyField(
                related_name="converged_derivations",
                to="grammar.DerivationStep",
            ),
        ),
        migrations.AddField(
            model_name="derivation",
            name="crashed_steps",
            field=models.ManyToManyField(
                related_name="crashed_derivations", to="grammar.DerivationStep"
            ),
        ),
        migrations.AddField(
            model_name="derivation",
            name="first_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="first_step_derivations",
                to="grammar.DerivationStep",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lexicalarrayitem",
            unique_together={("derivation_step", "lexical_item", "order")},
        ),
    ]
