# Generated by Django 2.1.7 on 2019-03-02 08:38

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [("lexicon", "0006_auto_20190201_1434")]

    operations = [
        migrations.CreateModel(
            name="Derivation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("ended", models.BooleanField()),
                ("converged", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="DerivationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("raw_lexical_array", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="DerivationStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("processed", models.BooleanField()),
                (
                    "derivations",
                    models.ManyToManyField(to="grammar.Derivation"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LexicalArray",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "derivation_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grammar.DerivationStep",
                    ),
                ),
                (
                    "lexical_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lexicon.LexicalItem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RuleDescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SyntacticObject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "lft",
                    models.PositiveIntegerField(db_index=True, editable=False),
                ),
                (
                    "rght",
                    models.PositiveIntegerField(db_index=True, editable=False),
                ),
                (
                    "tree_id",
                    models.PositiveIntegerField(db_index=True, editable=False),
                ),
                (
                    "level",
                    models.PositiveIntegerField(db_index=True, editable=False),
                ),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="grammar.SyntacticObject",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="SyntacticObjectValue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=100)),
                ("current_language", models.CharField(max_length=50)),
                (
                    "features",
                    models.ManyToManyField(blank=True, to="lexicon.Feature"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="syntacticobject",
            name="value",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="grammar.SyntacticObjectValue",
            ),
        ),
        migrations.AddField(
            model_name="derivationstep",
            name="lexical_array_tail",
            field=models.ManyToManyField(
                blank=True,
                through="grammar.LexicalArray",
                to="lexicon.LexicalItem",
            ),
        ),
        migrations.AddField(
            model_name="derivationstep",
            name="next_step",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_step",
                to="grammar.DerivationStep",
            ),
        ),
        migrations.AddField(
            model_name="derivationstep",
            name="root_so",
            field=mptt.fields.TreeOneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="grammar.SyntacticObject",
            ),
        ),
        migrations.AddField(
            model_name="derivationstep",
            name="rules",
            field=models.ManyToManyField(to="grammar.RuleDescription"),
        ),
        migrations.AddField(
            model_name="derivation",
            name="derivation_requests",
            field=models.ManyToManyField(to="grammar.DerivationRequest"),
        ),
        migrations.AddField(
            model_name="derivation",
            name="first_step",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="grammar.DerivationStep",
            ),
        ),
    ]
