# Generated by Django 2.1.7 on 2019-03-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("grammar", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="derivation", name="converged"),
        migrations.RemoveField(model_name="derivation", name="ended"),
        migrations.AddField(
            model_name="derivation",
            name="status",
            field=models.CharField(default="Pending", max_length=10),
        ),
    ]
