# Generated by Django 2.1.7 on 2019-09-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("grammar", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="derivationstep",
            name="complete",
            field=models.BooleanField(default=False),
        )
    ]
