# Generated by Django 2.1.7 on 2019-03-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("grammar", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="ruledescription",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ruledescription",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
