# Generated by Django 2.1.7 on 2019-04-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("grammar", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="derivationstep",
            name="generator_metadata_json",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="derivationstep",
            name="rule_errors_json",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="derivationstep",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processed", "Processed"),
                    ("Converged", "Converged"),
                    ("Crashed", "Crashed"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
