# Generated by Django 2.1.7 on 2019-04-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("grammar", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="syntacticobject",
            name="is_copy",
            field=models.BooleanField(default=False),
        )
    ]
