# Generated by Django 2.1.7 on 2019-03-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("grammar", "0001_initial")]

    operations = [
        migrations.RemoveField(
            model_name="derivation", name="derivation_requests"
        ),
        migrations.AddField(
            model_name="derivationrequest",
            name="derivations",
            field=models.ManyToManyField(to="grammar.Derivation"),
        ),
    ]
