# Generated by Django 2.1.7 on 2019-03-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("grammar", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="derivationrequest",
            name="completion_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="derivationrequest",
            name="derivations",
            field=models.ManyToManyField(
                related_name="derivation_requests", to="grammar.Derivation"
            ),
        ),
    ]
