# Generated by Django 2.1.7 on 2019-03-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("grammar", "0002_auto_20190304_2137")]

    operations = [
        migrations.AddField(
            model_name="derivationstep",
            name="crashed",
            field=models.BooleanField(default=False),
        )
    ]
