# Generated by Django 2.1.7 on 2019-03-03 17:02

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ("lexicon", "0006_auto_20190201_1434"),
        ("grammar", "0002_auto_20190302_2331"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lexicalarray", options={"ordering": ["order"]}
        ),
        migrations.RemoveField(
            model_name="derivationstep", name="lexical_array_tail"
        ),
        migrations.AlterField(
            model_name="derivation",
            name="first_step",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="grammar.DerivationStep",
            ),
        ),
        migrations.AlterField(
            model_name="derivationstep",
            name="root_so",
            field=mptt.fields.TreeOneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="grammar.SyntacticObject",
            ),
        ),
        migrations.AlterField(
            model_name="derivationstep",
            name="rules",
            field=models.ManyToManyField(
                blank=True, null=True, to="grammar.RuleDescription"
            ),
        ),
        migrations.AlterField(
            model_name="lexicalarray",
            name="derivation_step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lexical_array_tail",
                to="grammar.DerivationStep",
            ),
        ),
        migrations.AlterField(
            model_name="lexicalarray",
            name="lexical_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="lexicon.LexicalItem",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lexicalarray",
            unique_together={("derivation_step", "lexical_item", "order")},
        ),
    ]
