# Generated by Django 2.1.7 on 2019-03-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("grammar", "0002_generatordescription")]

    operations = [
        migrations.AddField(
            model_name="derivationstep",
            name="generators",
            field=models.ManyToManyField(
                blank=True, to="grammar.GeneratorDescription"
            ),
        )
    ]
