# Generated by Django 2.1.7 on 2019-04-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("grammar", "0002_auto_20190405_0647")]

    operations = [
        migrations.AlterField(
            model_name="derivationstep",
            name="generator_metadata_json",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="derivationstep",
            name="rule_errors_json",
            field=models.TextField(blank=True),
        ),
    ]
