# Generated by Django 2.1.7 on 2019-03-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("grammar", "0002_auto_20190307_0115")]

    operations = [
        migrations.AlterField(
            model_name="derivation",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Done", "Done"),
                    ("Crashed", "Crashed"),
                ],
                default="Pending",
                max_length=10,
            ),
        )
    ]
