# Generated by Django 2.1.7 on 2019-09-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("grammar", "0002_derivationstep_complete")]

    operations = [
        migrations.AddField(
            model_name="derivation",
            name="complete",
            field=models.BooleanField(default=False),
        )
    ]
