# Generated by Django 2.1.7 on 2019-04-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lexicon", "0001_initial"),
        ("grammar", "0003_auto_20190405_0648"),
    ]

    operations = [
        migrations.AddField(
            model_name="syntacticobjectvalue",
            name="deleted_features",
            field=models.ManyToManyField(
                blank=True, related_name="so_deleted", to="lexicon.Feature"
            ),
        )
    ]
