# Generated by Django 2.1.7 on 2019-04-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("grammar", "0003_derivationstep_generators")]

    operations = [
        migrations.AddField(
            model_name="derivationstep",
            name="crash_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="derivationstep",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Done", "Done"),
                    ("Crashed", "Crashed"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
