# Generated by Django 2.1.7 on 2019-03-03 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lexicon", "0006_auto_20190201_1434"),
        ("grammar", "0003_auto_20190304_0102"),
    ]

    operations = [
        migrations.CreateModel(
            name="LexicalArrayItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "derivation_step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lexical_array_items",
                        to="grammar.DerivationStep",
                    ),
                ),
                (
                    "lexical_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="lexicon.LexicalItem",
                    ),
                ),
            ],
            options={"ordering": ["order"]},
        ),
        migrations.AlterUniqueTogether(
            name="lexicalarray", unique_together=set()
        ),
        migrations.RemoveField(
            model_name="lexicalarray", name="derivation_step"
        ),
        migrations.RemoveField(model_name="lexicalarray", name="lexical_item"),
        migrations.DeleteModel(name="LexicalArray"),
        migrations.AlterUniqueTogether(
            name="lexicalarrayitem",
            unique_together={("derivation_step", "lexical_item", "order")},
        ),
    ]
