# Generated by Django 2.1.7 on 2019-03-06 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0003_auto_20190307_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='derivationstep',
            name='next_step',
        ),
        migrations.AddField(
            model_name='derivationstep',
            name='previous_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_steps', to='grammar.DerivationStep'),
        ),
        migrations.AddField(
            model_name='derivationstep',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Crashed', 'Crashed')], default='Pending', max_length=10),
        ),
    ]
