# Generated by Django 2.1.7 on 2019-04-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("grammar", "0004_syntacticobjectvalue_deleted_features")]

    operations = [
        migrations.AlterField(
            model_name="syntacticobjectvalue",
            name="deleted_features",
            field=models.ManyToManyField(
                blank=True,
                related_name="sovalue_deleted_set",
                to="lexicon.Feature",
            ),
        ),
        migrations.AlterField(
            model_name="syntacticobjectvalue",
            name="features",
            field=models.ManyToManyField(
                blank=True, related_name="sovalue_set", to="lexicon.Feature"
            ),
        ),
    ]
