# Generated by Django 2.1.7 on 2019-03-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lexicon", "0006_auto_20190201_1434"),
        ("grammar", "0004_auto_20190304_0119"),
    ]

    operations = [
        migrations.AddField(
            model_name="derivationstep",
            name="lexical_array_tail",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                through="grammar.LexicalArrayItem",
                to="lexicon.LexicalItem",
            ),
        )
    ]
