# Generated by Django 2.1.7 on 2019-03-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("grammar", "0005_derivationstep_lexical_array_tail")]

    operations = [
        migrations.AlterField(
            model_name="derivationstep",
            name="processed",
            field=models.BooleanField(default=False),
        )
    ]
