# Generated by Django 2.1.7 on 2019-04-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("grammar", "0005_auto_20190401_0635")]

    operations = [
        migrations.AlterField(
            model_name="derivationstep",
            name="crash_reason",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="derivationstep",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Okay", "Okay"),
                    ("Converged", "Converged"),
                    ("Crashed", "Crashed"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
