# Generated by Django 2.1.7 on 2019-04-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lexicon", "0001_initial"),
        ("grammar", "0005_auto_20190405_1108"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="syntacticobjectvalue", name="deleted_features"
        ),
        migrations.RemoveField(
            model_name="syntacticobjectvalue", name="features"
        ),
        migrations.RemoveField(model_name="syntacticobject", name="value"),
        migrations.AddField(
            model_name="syntacticobject",
            name="current_language",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="syntacticobject",
            name="deleted_features",
            field=models.ManyToManyField(
                blank=True, related_name="so_deleted_set", to="lexicon.Feature"
            ),
        ),
        migrations.AddField(
            model_name="syntacticobject",
            name="features",
            field=models.ManyToManyField(
                blank=True, related_name="so_set", to="lexicon.Feature"
            ),
        ),
        migrations.AddField(
            model_name="syntacticobject",
            name="text",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(name="SyntacticObjectValue"),
    ]
