# Generated by Django 2.1.7 on 2019-03-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("grammar", "0006_auto_20190304_0211")]

    operations = [
        migrations.AlterField(
            model_name="derivation",
            name="converged",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="derivation",
            name="ended",
            field=models.BooleanField(default=False),
        ),
    ]
