# Generated by Django 2.1.7 on 2019-04-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("lexicon", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="properties",
            field=models.ManyToManyField(blank=True, to="lexicon.FeatureProperty"),
        )
    ]
