# Generated by Django 2.1.5 on 2019-01-30 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("lexicon", "0002_auto_20190130_0040")]

    operations = [
        migrations.RemoveField(model_name="featureset", name="features"),
        migrations.DeleteModel(name="FeatureSet"),
    ]
