# Generated by Django 2.1.5 on 2019-02-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("lexicon", "0005_auto_20190131_0114")]

    operations = [
        migrations.RenameField(
            model_name="featureproperty",
            old_name="value",
            new_name="raw_value",
        ),
        migrations.AddField(
            model_name="featureproperty",
            name="type",
            field=models.CharField(
                choices=[
                    ["Boolean", "Boolean"],
                    ["Text", "Text"],
                    ["Integer", "Integer"],
                ],
                default="Text",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lexicalitem",
            name="features",
            field=models.ManyToManyField(blank=True, to="lexicon.Feature"),
        ),
        migrations.AlterUniqueTogether(
            name="featureproperty", unique_together={("name", "raw_value")}
        ),
    ]
